// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtODIL39KOnYoymjZOIFVq66nzO-dioj4',
    appId: '1:645953637082:web:e01614b661103125e973e3',
    messagingSenderId: '645953637082',
    projectId: 'iti-firebase-a5b46',
    authDomain: 'iti-firebase-a5b46.firebaseapp.com',
    storageBucket: 'iti-firebase-a5b46.appspot.com',
    measurementId: 'G-ZTEZ37WVQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBryr4ZCqNQ-qEiS7AWXok-TXw_3tqfzPY',
    appId: '1:645953637082:android:1a5ddb5634d10aeee973e3',
    messagingSenderId: '645953637082',
    projectId: 'iti-firebase-a5b46',
    storageBucket: 'iti-firebase-a5b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4KIlq2KdHPbFa4ooRj3a3xZngNXigZOM',
    appId: '1:645953637082:ios:e47942356b24b7dbe973e3',
    messagingSenderId: '645953637082',
    projectId: 'iti-firebase-a5b46',
    storageBucket: 'iti-firebase-a5b46.appspot.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4KIlq2KdHPbFa4ooRj3a3xZngNXigZOM',
    appId: '1:645953637082:ios:fb7ceb272a5da2cbe973e3',
    messagingSenderId: '645953637082',
    projectId: 'iti-firebase-a5b46',
    storageBucket: 'iti-firebase-a5b46.appspot.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
